databases:
  - name: webhook_test
    databaseName: webhook_test
    user: webhook_test
    plan: free

services:
  - type: web
    plan: free
    name: webhook_test
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook_test
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
